### ISSUE TITLE
Error when `inherit`ing string attribute names

### ISSUE THREAD

**Issue by 9999years** [NixOS/nixfmt#174] opened 2024-03-27 20:31 UTC
### Description

`nixfmt` errors when strings are used as attribute names in `inherit` statements.

### Example input

```nix
let
  a = {
    puppy = 1;
  };
in {
  inherit (a) "puppy";
}
```

### Actual output

```
$ nixfmt string-attr-name.nix
string-attr-name.nix:6:15:
  |
6 |   inherit (a) "puppy";
  |               ^
unexpected '"'
expecting expression
```

Additionally, the error message is confusing because `"puppy"` is an expression.

**Comment by piegamesde** [comment] 2024-03-28 06:57
Hi, I cannot reproduce this issue. Could you please make sure you are using the latest `master` branch (or the `nixfmt-rfc-style` package) and try again?

**Comment by tomberek** [comment] 2024-03-31 18:38
Unable to reproduce on `master` branch, but it does happen for tag `v0.6.0`. Closing as fixed.

**Closed by tomberek** 2024-03-31 18:38 UTC
